import AirlockCore
import AirlockRuntime
import CryptoKit
import Foundation

/// The image layer with a project's tools: mise installs them, apt adds Debian packages.
/// Tagged by content, so each distinct stack is built once and reused by every task.
enum StackImage {
    /// `parent` unchanged when the stack needs nothing beyond the agent image.
    static func recipe(for stack: ProjectStack, learnedPackages: [String], parent: ImageRecipe, paths: Paths) throws -> ImageRecipe {
        let dockerfile = dockerfile(for: stack, learnedPackages: learnedPackages)
        guard let dockerfile else { return parent }
        let digest = SHA256.hash(data: Data(dockerfile.utf8)).map { String(format: "%02x", $0) }.joined().prefix(16)
        let dir = paths.root.appending(path: "stacks/\(digest)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try Data(dockerfile.utf8).write(to: dir.appending(path: "Dockerfile"), options: .atomic)
        return ImageRecipe(name: "stack", contextDirectory: dir, parent: parent)
    }

    static func dockerfile(for stack: ProjectStack, learnedPackages: [String]) -> String? {
        let packages = (stack.packages + learnedPackages).reduce(into: [String]()) { if !$0.contains($1) { $0.append($1) } }
            .filter(isInstallable)
        let tools = stack.tools.sorted { $0.key < $1.key }
            .filter { Self.isSafe($0.key) && Self.isSafe($0.value) }
            .map { "\($0.key)@\($0.value)" }
        guard !packages.isEmpty || !tools.isEmpty else { return nil }
        var lines = ["# Generated by AIrlock: this project's tools.", "ARG BASE_IMAGE", "FROM ${BASE_IMAGE}"]
        if !packages.isEmpty {
            lines.append("RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \(packages.joined(separator: " ")) && rm -rf /var/lib/apt/lists/*")
        }
        if !tools.isEmpty {
            lines += ["USER node", "RUN mise use -g \(tools.joined(separator: " ")) && mise reshim", "USER root"]
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Packages that hand out root; `airlock-install-handler` refuses the same ones.
    static let forbiddenPackages: Set<String> = [
        "sudo", "sudo-ldap", "doas", "opendoas", "gosu", "su-exec", "policykit-1", "pkexec", "polkitd", "super", "really", "calife",
    ]

    /// A Debian package name AIrlock will put in an image. Learned packages come from inside
    /// a task, so they're checked here too, not only by the handler that installed them.
    static func isInstallable(_ name: String) -> Bool {
        name.range(of: #"^[a-z0-9][a-z0-9+.-]+$"#, options: .regularExpression) != nil && !forbiddenPackages.contains(name)
    }

    /// Tool names and versions go into a RUN line, so only plain characters.
    static func isSafe(_ text: String) -> Bool {
        !text.isEmpty && text.allSatisfy { $0.isLetter || $0.isNumber || "._-:/".contains($0) }
    }
}
